export const plans = [
  {
    id: 1,
    title: "FREE",
    price: "",
    btn_title: "Free plan",
    btn_color: "#1eee",
    d_1: "5 uploads daily",
    d_2: "Standart file upload size",
    d_3: "Limited URLs processing",
  },
  {
    id: 2,
    title: "PLUS",
    price: "USD $49/mo",
    btn_title: "Subscribe",
    btn_color: "#1eee",
    d_1: "25 uploads daily",
    d_2: "Extended file upload size",
    d_3: "Extended URLs processing including secure websites",
  },
  {
    id: 3,
    title: "ENTERPRISE",
    price: "",
    btn_title: "Contact Us",
    btn_color: "#1eee",
    d_1: "Unlimited uploads",
    d_2: "Unlimited URLs processing",
    d_3: "On premise installation (no internet connection)",
  },
];
