FROM node:14 as build

ARG BASE_URL
ARG CONVERSION_URL
ARG FIREBASE_APIKEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_PROJECTID
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDERId
ARG FIREBASE_APPId
ARG FIREBASE_MEASUREMENT_Id
ARG LOGGING

ENV REACT_APP_BASE_URL=$BASE_URL
ENV REACT_APP_CONVERSION_URL=$CONVERSION_URL
ENV REACT_APP_FIREBASE_APIKEY=$FIREBASE_APIKEY
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV REACT_APP_FIREBASE_PROJECTID=$FIREBASE_PROJECTID
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ENV REACT_APP_FIREBASE_MESSAGING_SENDERId=$FIREBASE_MESSAGING_SENDERId
ENV REACT_APP_FIREBASE_APPId=$FIREBASE_APPId
ENV REACT_APP_FIREBASE_MEASUREMENT_Id=$FIREBASE_MEASUREMENT_Id
ENV LOGGING=$LOGGING

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps --cache .npm --prefer-offline
COPY . .

RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
